# Generated by Django 4.0.4 on 2022-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='details',
            name='food',
            field=models.CharField(choices=[('Egg', 'Egg'), ('Food', 'Food'), ('BedSheets', 'BedSheets'), ('Stationary', 'Stationary'), ('Dress', 'Dress')], default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='details',
            name='trust',
            field=models.CharField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], default=True, max_length=200),
        ),
    ]
