# Generated by Django 4.0.4 on 2022-10-28 19:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_alter_details_food_alter_details_trust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='food',
        ),
        migrations.AddField(
            model_name='details',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Egg', 'Egg'), ('Food', 'Food'), ('BedSheets', 'BedSheets'), ('Stationary', 'Stationary'), ('Dress', 'Dress')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='trust',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], max_length=200, null=True),
        ),
    ]
