# Generated by Django 4.1.2 on 2022-10-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_alter_details_image_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='date_of_birth',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='details',
            name='category',
        ),
        migrations.AddField(
            model_name='details',
            name='bedsheets',
            field=models.CharField(default='bedsheets', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='dress',
            field=models.CharField(default='dress', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='egg',
            field=models.CharField(default='Egg', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='food',
            field=models.CharField(default='Food', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='stationary',
            field=models.CharField(default='Stationary', max_length=200, null=True),
        ),
    ]
