# Generated by Django 4.1.2 on 2022-10-31 08:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_rename_date_of_birth_details_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='trust',
        ),
        migrations.AlterField(
            model_name='details',
            name='bedsheets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dress',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='egg',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='food',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stationary',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], max_length=200, null=True),
        ),
    ]
