# Generated by Django 4.1.2 on 2022-11-03 09:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_remove_details_trust_alter_details_bedsheets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='price',
        ),
        migrations.AddField(
            model_name='details',
            name='bedsheetsprice',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='bedsheetsquantity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='dressprice',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='dressquantity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='eggprice',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='eggquantity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='foodprice',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='foodquantity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='stationaryprice',
            field=models.CharField(default='none', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='stationaryquantity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='bedsheets',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dress',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='egg',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='food',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stationary',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], default='none', max_length=200, null=True),
        ),
    ]
