# Generated by Django 4.1.2 on 2022-11-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0011_remove_details_price_details_bedsheetsprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='bedsheetsquantity',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dressquantity',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='eggquantity',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='foodquantity',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stationaryquantity',
            field=models.CharField(default='none', max_length=20, null=True),
        ),
    ]
