# Generated by Django 4.1.2 on 2022-11-04 06:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0012_alter_details_bedsheetsquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='bedsheetsprice',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='bedsheetsquantity',
            field=models.CharField(blank=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dressprice',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='dressquantity',
            field=models.CharField(blank=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='egg',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MotherTeresa', 'MotherTeresa'), ('AnnaiTeresa', 'AnnaiTeresa'), ('BlindSchool', 'BlindSchool'), ('Henry', 'Henry'), ('DonBoscoAnbuIllam', 'DonBoscoAnbuIllam')], default='0000000', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='eggprice',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='eggquantity',
            field=models.CharField(blank=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='foodprice',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='foodquantity',
            field=models.CharField(blank=True, default='none', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stationaryprice',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='stationaryquantity',
            field=models.CharField(blank=True, default='none', max_length=20, null=True),
        ),
    ]
