# Generated by Django 4.1.2 on 2022-11-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0013_alter_details_bedsheetsprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
            ],
        ),
    ]
