# Generated by Django 4.1.2 on 2022-11-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0015_event_delete_trust'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
