# Generated by Django 4.0.4 on 2022-11-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0016_event_complete_event_price_alter_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
